// CPP_AddIn.idl : IDL source for CPP_AddIn
//

// This file will be processed by the MIDL tool to
// produce the type library (CPP_AddIn.tlb) and marshalling code.

import "oaidl.idl";

[
	object,
	uuid(91e702f2-d64d-48e3-b5dd-9afaeead3a00),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IConnect : IDispatch
{
};

[
	object,
	uuid(3c8bd09f-3ba0-4992-be24-b6c17dc7e78a),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IItemWrapper : IDispatch
{
};
[
	uuid(f3eda8a5-30af-4dc3-875b-075167f21b10),
	version(1.0),
]
library CPP_AddInLib
{
	importlib("stdole2.tlb");
	[
		uuid(69eb1c58-6e7e-420e-b339-6271f804e966)
	]
	coclass Connect
	{
		[default] interface IConnect;
	};
	[
		uuid(da1194fa-238a-4f0e-8f55-d01c37b39787)
	]
	coclass ItemWrapper
	{
		[default] interface IItemWrapper;
	};
};


import "shobjidl.idl";

