// CPP_AddIn.idl : IDL source for CPP_AddIn
//

// This file will be processed by the MIDL tool to
// produce the type library (CPP_AddIn.tlb) and marshalling code.

import "oaidl.idl";

[uuid(000C03A7-0000-0000-C000-000000000046)]
interface IRibbonUI {};

[uuid(000C0395-0000-0000-C000-000000000046)]
interface IRibbonControl {};

[
	uuid(f3eda8a5-30af-4dc3-875b-075167f21b10),
	version(1.0),
	helpstring("CPP_AddIn 1.0 Type Library")
]
library CPP_AddInLib
{
	// This is the IRibbonCallback implementation that allows implementing callback methods
	// for ribbon controls
	[
			object,
			uuid(0fea223e-70a6-43b3-aa0d-9f2c9fd69d23),
			dual,
			nonextensible,
			helpstring("IRibbonCallback Interface"),
			pointer_default(unique)
	]
	interface IRibbonCallback : IDispatch
	{
		[id(1), helpstring("OnCreateCustomView")] HRESULT OnCreateCustomView([in] IRibbonControl *pRibbonControl);
	};

	// This is the default Connect class
	importlib("stdole2.tlb");
	[
		uuid(69eb1c58-6e7e-420e-b339-6271f804e966),
		helpstring("Connect Class")
	]
	coclass Connect
	{
		[default] interface IRibbonCallback;
	};
};


import "shobjidl.idl";

